"""baseline schema

Revision ID: 42c331da3ed0
Revises: 
Create Date: 2026-09-16 10:49:09.451393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42c331da3ed0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievement_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('education_level',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('exams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('regions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('statement_statuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('type_study',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('universities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('short_name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('official_url', sa.String(length=500), nullable=True),
    sa.Column('logo', sa.String(length=500), nullable=True),
    sa.Column('id_region', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_region'], ['regions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_universities_name'), 'universities', ['name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('patronymic', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('passport', sa.String(length=50), nullable=True),
    sa.Column('snils', sa.String(length=20), nullable=True),
    sa.Column('education', sa.Text(), nullable=True),
    sa.Column('id_region', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['id_region'], ['regions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('passport'),
    sa.UniqueConstraint('snils')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('achievement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('id_category', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_category'], ['achievement_categories.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_user'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('faculties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('short_name', sa.String(length=100), nullable=True),
    sa.Column('official_url', sa.String(length=500), nullable=True),
    sa.Column('id_university', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_university'], ['universities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_faculties_id_university'), 'faculties', ['id_university'], unique=False)
    op.create_index(op.f('ix_faculties_name'), 'faculties', ['name'], unique=False)
    op.create_table('user_exam',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('id_exam', sa.Integer(), nullable=False),
    sa.Column('score_achieved', sa.Integer(), nullable=False),
    sa.CheckConstraint('score_achieved >= 0', name='ck_user_exam_score'),
    sa.ForeignKeyConstraint(['id_exam'], ['exams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_user'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_user', 'id_exam', name='uq_user_exam')
    )
    op.create_table('programs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('official_url', sa.String(length=500), nullable=True),
    sa.Column('duration_years', sa.Integer(), nullable=False),
    sa.Column('budget_places', sa.Integer(), nullable=False),
    sa.Column('paid_places', sa.Integer(), nullable=False),
    sa.Column('tuition_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id_type_study', sa.Integer(), nullable=False),
    sa.Column('id_education_level', sa.Integer(), nullable=False),
    sa.Column('id_faculty', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_education_level'], ['education_level.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_faculty'], ['faculties.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_type_study'], ['type_study.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_programs_code'), 'programs', ['code'], unique=False)
    op.create_index(op.f('ix_programs_id_faculty'), 'programs', ['id_faculty'], unique=False)
    op.create_index(op.f('ix_programs_name'), 'programs', ['name'], unique=False)
    op.create_table('comparisons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('id_program_1', sa.Integer(), nullable=False),
    sa.Column('id_program_2', sa.Integer(), nullable=False),
    sa.Column('selected_program_id', sa.Integer(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('id_program_1 <> id_program_2', name='ck_comparison_different_programs'),
    sa.ForeignKeyConstraint(['id_program_1'], ['programs.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_program_2'], ['programs.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_user'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['selected_program_id'], ['programs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comparisons_id_user'), 'comparisons', ['id_user'], unique=False)
    op.create_table('program_exam',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_program', sa.Integer(), nullable=False),
    sa.Column('id_exam', sa.Integer(), nullable=False),
    sa.Column('passing_score', sa.Integer(), nullable=True),
    sa.CheckConstraint('passing_score IS NULL OR passing_score >= 0', name='ck_program_exam_passing_score'),
    sa.ForeignKeyConstraint(['id_exam'], ['exams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_program'], ['programs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_program', 'id_exam', name='uq_program_exam')
    )
    op.create_table('recommendation_program_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('id_program', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['id_program'], ['programs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_user'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendation_program_user_id_user'), 'recommendation_program_user', ['id_user'], unique=False)
    op.create_table('statement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('id_program', sa.Integer(), nullable=False),
    sa.Column('id_status', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['id_program'], ['programs.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_status'], ['statement_statuses.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_user'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_statement_id_program'), 'statement', ['id_program'], unique=False)
    op.create_index(op.f('ix_statement_id_user'), 'statement', ['id_user'], unique=False)
    op.create_table('user_programs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('id_program', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['id_program'], ['programs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_user'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_user', 'id_program', name='uq_user_program')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_programs')
    op.drop_index(op.f('ix_statement_id_user'), table_name='statement')
    op.drop_index(op.f('ix_statement_id_program'), table_name='statement')
    op.drop_table('statement')
    op.drop_index(op.f('ix_recommendation_program_user_id_user'), table_name='recommendation_program_user')
    op.drop_table('recommendation_program_user')
    op.drop_table('program_exam')
    op.drop_index(op.f('ix_comparisons_id_user'), table_name='comparisons')
    op.drop_table('comparisons')
    op.drop_index(op.f('ix_programs_name'), table_name='programs')
    op.drop_index(op.f('ix_programs_id_faculty'), table_name='programs')
    op.drop_index(op.f('ix_programs_code'), table_name='programs')
    op.drop_table('programs')
    op.drop_table('user_exam')
    op.drop_index(op.f('ix_faculties_name'), table_name='faculties')
    op.drop_index(op.f('ix_faculties_id_university'), table_name='faculties')
    op.drop_table('faculties')
    op.drop_table('achievement')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_universities_name'), table_name='universities')
    op.drop_table('universities')
    op.drop_table('type_study')
    op.drop_table('statement_statuses')
    op.drop_table('regions')
    op.drop_table('exams')
    op.drop_table('education_level')
    op.drop_table('achievement_categories')
    # ### end Alembic commands ###
