"""add diplomas drop passport snils

Revision ID: f4a480f91d6e
Revises: 42c331da3ed0
Create Date: 2026-09-16 18:32:03.051151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4a480f91d6e'
down_revision: Union[str, None] = '42c331da3ed0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diploma_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('diplomas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('id_diploma_type', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('institution', sa.String(length=255), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('average_score', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['id_diploma_type'], ['diploma_types.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_user'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diplomas_id_user'), 'diplomas', ['id_user'], unique=False)
    op.drop_constraint(op.f('users_passport_key'), 'users', type_='unique')
    op.drop_constraint(op.f('users_snils_key'), 'users', type_='unique')
    op.drop_column('users', 'snils')
    op.drop_column('users', 'passport')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('passport', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('snils', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.create_unique_constraint(op.f('users_snils_key'), 'users', ['snils'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('users_passport_key'), 'users', ['passport'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_diplomas_id_user'), table_name='diplomas')
    op.drop_table('diplomas')
    op.drop_table('diploma_types')
    # ### end Alembic commands ###
